//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Updater.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_AppUpdate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_AppUpdate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Updater.Properties.Resources.AppUpdate", typeof(Resources_AppUpdate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общее.
        /// </summary>
        public static string Category_Common {
            get {
                return ResourceManager.GetString("Category.Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расположение обновления.
        /// </summary>
        public static string Category_UpdateLocation {
            get {
                return ResourceManager.GetString("Category.UpdateLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каталог с файлом обновления.
        /// </summary>
        public static string Config_Folder_Description {
            get {
                return ResourceManager.GetString("Config.Folder.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Папка.
        /// </summary>
        public static string Config_Folder_DisplayName {
            get {
                return ResourceManager.GetString("Config.Folder.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ГитХаб.
        /// </summary>
        public static string Config_GitHub_Description {
            get {
                return ResourceManager.GetString("Config.GitHub.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ГитХаб.
        /// </summary>
        public static string Config_GitHub_DisplayName {
            get {
                return ResourceManager.GetString("Config.GitHub.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расположение исполняемого файла..
        /// </summary>
        public static string Config_LocalFile_Description {
            get {
                return ResourceManager.GetString("Config.LocalFile.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программа.
        /// </summary>
        public static string Config_LocalFile_DisplayName {
            get {
                return ResourceManager.GetString("Config.LocalFile.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расположение обновления.
        /// </summary>
        public static string Config_Location_Description {
            get {
                return ResourceManager.GetString("Config.Location.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расположение.
        /// </summary>
        public static string Config_Location_DisplayName {
            get {
                return ResourceManager.GetString("Config.Location.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Папка.
        /// </summary>
        public static string Config_Location_Folder_Description {
            get {
                return ResourceManager.GetString("Config.Location.Folder.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ГитХаб.
        /// </summary>
        public static string Config_Location_GitHub_Description {
            get {
                return ResourceManager.GetString("Config.Location.GitHub.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архив с обновлением.
        /// </summary>
        public static string Folder_ArchiveFile_Description {
            get {
                return ResourceManager.GetString("Folder.ArchiveFile.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архив.
        /// </summary>
        public static string Folder_ArchiveFile_DisplayName {
            get {
                return ResourceManager.GetString("Folder.ArchiveFile.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каталог с файлом обновления.
        /// </summary>
        public static string Folder_Path_Description {
            get {
                return ResourceManager.GetString("Folder.Path.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Папка.
        /// </summary>
        public static string Folder_Path_DisplayName {
            get {
                return ResourceManager.GetString("Folder.Path.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл с номером версии обновления.
        /// </summary>
        public static string Folder_VersionFile_Description {
            get {
                return ResourceManager.GetString("Folder.VersionFile.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл версии.
        /// </summary>
        public static string Folder_VersionFile_DisplayName {
            get {
                return ResourceManager.GetString("Folder.VersionFile.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архив с обновлением.
        /// </summary>
        public static string GitHub_ArchiveFile_Description {
            get {
                return ResourceManager.GetString("GitHub.ArchiveFile.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архив.
        /// </summary>
        public static string GitHub_ArchiveFile_DisplayName {
            get {
                return ResourceManager.GetString("GitHub.ArchiveFile.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Владелец.
        /// </summary>
        public static string GitHub_Owner_Description {
            get {
                return ResourceManager.GetString("GitHub.Owner.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Владелец.
        /// </summary>
        public static string GitHub_Owner_DisplayName {
            get {
                return ResourceManager.GetString("GitHub.Owner.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Репозиторий.
        /// </summary>
        public static string GitHub_Repo_Description {
            get {
                return ResourceManager.GetString("GitHub.Repo.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Репозиторий.
        /// </summary>
        public static string GitHub_Repo_DisplayName {
            get {
                return ResourceManager.GetString("GitHub.Repo.DisplayName", resourceCulture);
            }
        }
    }
}
